#!/usr/bin/env bash

remote="${1:-$(git remote-name)}"
branch="${2:-$(git upstream-branch | sed -E -e $"s|[^/]+/||")}"

if [[ "${remote}" != "." ]]; then
    git fetch -q "${remote}" || true
    branch="${remote}/${branch}"
fi
git --no-pager log "${branch}..HEAD"
