#
# source code repositories
#
Host github github.com
   User git
   Hostname github.com
   IdentitiesOnly yes
   IdentityFile ~/.ssh/id_rsa
   IdentityFile ~/.ssh/id_ed25519_sk_miroslaw@11514433.pub
   IdentityFile ~/.ssh/id_mb_ed25519
   PubkeyAuthentication true
   PreferredAuthentications publickey
